backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
# Uncomment local_backend when you need to develop in your local
local_backend: false # run npx netlify-cms-proxy-server for local testing
collections:
  - name: "pages"
    label: "Sivut"
    files:
    - label: "Etusivu"
      name: "home"
      file: "content/home.json"
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string"}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string"}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "string"}
            - { label: "Toimintakehotteen teksti", name: "CTAText", widget: "string"}
            - { label: "Linkki", name: "CTALink", widget: "string"}
            - { label: "Näytetäänkö Vaalinumero?", name: "DisplayElectionNumber", widget: "boolean"}
            - { label: "Vaalinumero", name: "ElectionNumber", widget: "string"}
        - label: 'Teemat-osio'
          name: "ThemeSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string" }  
          - label: "Teemat"
            name: "themes"
            widget: list
            fields:
              - { label: "Teeman otsikko", name: "title", widget: "string"}
              - { label: "Kuvaus", name: "description", widget: "text"}
              - { label: "Kuva", name: "image", widget: "image" }
              - { label: "Napin teksti", name: "cta", widget: "string"}
              - { label: "Linkki", name: "link", widget: "string"}
        - label: "Referenssit-osio"
          name: "ReferenceSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string" }  
          - label: "Referenssit"
            name: "referees"
            widget: list
            fields:
              - { label: "Referoija", name: "referee", widget: "string"}
              - { label: "Referoijan nimike", name: "refereeTitle", widget: "string"}
              - { label: "Referenssi", name: "reference", widget: "text"}
              - { label: "Kuva", name: "image", widget: "image" }
        - label: "Sivuston metatiedot"
          name: "meta"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string"}
          - { label: "Sivun kuvaus", name: "description", widget: "Vahvan talouden Turku"}
          - { label: "Sivun linkki", name: "url", widget: "string"}
          - { label: "Sivun kuva", name: "image", widget: "image"}
    - label: "Vaaliteemat"
      name: "themes"
      file: content/themes.json
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string"}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string"}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image"}
        - label: 'Teemat-osio'
          name: "ThemeSection"
          widget: object
          fields:
          - label: "Teemat"
            name: "themes"
            widget: list
            fields:
              - { label: "Teeman otsikko", name: "title", widget: "string"}
              - { label: "Kuvaus", name: "description", widget: "text"}
              - { label: "Kuva", name: "image", widget: "image" }
    - label: "Koli"
      name: "aboutMe"
      file: "content/aboutMe.json"
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string"}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string"}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image"}
        - label: "Usein kysytyt kysymykset"
          name: "FAQSection"
          widget: object
          fields:
            - { label: "Pöytäkoneen Profiilikuva", name: "faqProfilePicture", widget: "image"}
            - { label: "Profiilikuva selvennys", name: "faqProfilePictureAlt", widget: "string"}
            - label: "Kysymykset"
              name: "faqs"
              widget: list
              fields:
                - { label: "Kysymys", name: "question", widget: "string"}
                - { label: "Vastaus", name: "answer", widget: "text"}
                - { label: "Vastaus näkyvissä?", name: "open", widget: "boolean" }
    - label: "Yhteydenotto"
      name: "contact"
      file: "content/contact.json"
      fields:
        - label: "Yhteydenotto"
          name: "ContactSection"
          widget: object
          fields: 
            - { label: "Otsikko", name: "SectionTitle", widget: "string"}
            - { label: "Kuvaus", name: "SectionDescription", widget: "text"}
            -   label: "Sosiaalinen Media"
                name: "socialMedia"
                widget: list
                collapsed: true
                hint: "Täällä voit lisätä somesi, Klikkaa 'Add social icons'"
                fields:
                  - label: "Icons"
                    name: "icon"
                    widget: "select"
                    options:
                      [
                        "Twitter",
                        "LinkedIn",
                        "Instagram",
                        "Email",
                        "Phone",
                      ]
                    hint: "Valitse ikoni"
                  - widget: string
                    name: url
                    label: url
                    required: true
                    hint: "Laita tähän URL:i SoMe kanavaasi"
  - name: "general"
    label: "Sivun asetukset"
    files:
    - label: "Yleiset osiot"
      name: "site"
      file: "content/site.json"
      fields:
        - label: "Yläpalkki"
          name: "Header"
          widget: object
          fields:
           - { label: "Logo", name: "logo", widget: "string"}
           - { label: "Mobiili Kokoomuslogo", name: "mobileImageLogo", widget: "image"}
           - { label: "Mobiiliu Kokoomuslogon täsmennys", name: "mobileImageAlt", widget: "string"}
           - { label: "Etusivu", name: "homeTitle", widget: "string"}
           - { label: "Vaaliteemat", name: "themesTitle", widget: "string"}
           - { label: "Juho", name: "aboutMeTitle", widget: "string"}
           - { label: "Ota Yhteyttä", name: "contactTitle", widget: "string"}
        - label: "Uutiskirje"
          name: "newsletter"
          widget: object
          fields:
          - { label: "Logo", name: "logo", widget: "image"}
          - { label: "Otsikko", name: "title", widget: "string"}
          - { label: "kuvaus", name: "description", widget: "string"}
          - { label: "Toimintakehotteen teksti", name: "cta", widget: "string"}
          - { label: "Taustakuva", name: "backgroundImage", widget: "image"}
        - label: "Alapalkki"
          name: "Footer"
          widget: object
          fields:
           - { label: "Pöytäkoneen Kokoomuslogo", name: "desktopLogoImage", widget: "image"}
           - { label: "Kokoomuslogon täsmennys", name: "desktopLogoAlt", widget: "string"}
           -    label: "Sosiaalinen Media"
                name: "socialMedia"
                widget: list
                collapsed: true
                hint: "Täällä voit lisätä somesi, Klikkaa 'Add social icons'"
                fields:
                  - label: "Icons"
                    name: "icon"
                    widget: "select"
                    options:
                      [
                        "Twitter",
                        "LinkedIn",
                        "Instagram",
                        "Email",
                        "Phone",
                      ]
                    hint: "Valitse ikoni"
                  - widget: string
                    name: url
                    label: url
                    required: true
                    hint: "Laita tähän URL:i SoMe kanavaasi"
            